version: 2.1
# Use a package of configuration called an orb.
orbs:
  node: circleci/node@1.1.6

commands:
  install-dependencies:
    description: "Install dependencies"
    steps:
      - run: npm install
  run-unit-tests:
      steps:
        - run: npm run test
  lint:
    steps:
      - run: npm run lint
  compile:
    steps:
      - run: npm run compile
  create-npm-rc:
    description: "Create .npmrc file"
    steps:
      - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc
  publish-on-npm:
    description: "Publish on npm.org"
    steps:
      - run: npm publish --access public
  generate-docs:
    description: "Generating TSDoc"
    steps:
      - run: npm run generate-docs
  publish-docs:
    description: "Publish generated docs on firebase"
    steps:
      - run: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN"
jobs:
  lint:
    executor:
      name: node/default
    steps:
      - checkout
      - install-dependencies
      - compile
      - lint
  publish:
    executor: 
      name: node/default
    steps:
      - checkout
      - install-dependencies
      - compile
      - create-npm-rc
      - publish-on-npm
  deploy-docs:
      executor: 
        name: node/default
      steps:
        - checkout
        - install-dependencies
        - generate-docs
        - publish-docs
workflows:
  build:
    jobs:
      - lint
      - deploy-docs:
          context:
            - org-global
            - makepad-firebase
          requires:
            - lint
          filters:
            tags:
              only:
                # matches stable version tags
                # matches release candidate (aka rc) tags
                # v1.10.10
                # v1.0.0-rc1
                - /^v([0-9]+\.){2}[0-9](-rc[0-9]+)?$/       
      - publish:
          context:
            - org-global
            - makepad-npm
          requires:
            - lint
          filters:
            tags:
              only:
                # matches stable version tags
                # matches release candidate (aka rc) tags
                # v1.10.10
                # v1.0.0-rc1
                - /^v([0-9]+\.){2}[0-9](-rc[0-9]+)?$/             